browser = chrome
url = https://dev01.ip.wawa.com/catering
store_name = media
city = Media
state = PA, USA
first_name = test
last_name = syed
Email = syed.khan@wawa.com
phoneNumber = 6505555555
cardNumber = 4111 1111 1111 1111
Expiredate = 12/29
CCV = 123
cardname = syed
Address = 19th street
city = texas
state = tx
zipcode = 89105